package com.AirplaneCoordinates.Core.PreciseDecimal;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class PreciseDecimalOperationsTest {
    @Test
    public final void sum() {
        assertEquals(
            PreciseDecimalOperations.sum(
                PreciseDecimal.from(4),
                PreciseDecimal.from(2)
            ),
            PreciseDecimal.from(6)
        );
        assertEquals(
            PreciseDecimalOperations.sum(
                PreciseDecimal.from(-1),
                PreciseDecimal.from(2)
            ),
            PreciseDecimal.from(1)
        );
        assertEquals(
            PreciseDecimalOperations.sum(
                PreciseDecimal.from(7),
                PreciseDecimal.from(-3)
            ),
            PreciseDecimal.from(4)
        );
        assertEquals(
            PreciseDecimalOperations.sum(
                PreciseDecimal.from(3),
                PreciseDecimal.from(-3)
            ),
            PreciseDecimal.from(0)
        );
        assertEquals(
            PreciseDecimalOperations.sum(
                PreciseDecimal.from(7),
                PreciseDecimal.from(0)
            ),
            PreciseDecimal.from(7)
        );
    }

    @Test
    public final void sub() {
        assertEquals(
            PreciseDecimalOperations.sub(
                PreciseDecimal.from(6),
                PreciseDecimal.from(4)
            ),
            PreciseDecimal.from(2)
        );
        assertEquals(
            PreciseDecimalOperations.sub(
                PreciseDecimal.from(-1),
                PreciseDecimal.from(1)
            ),
            PreciseDecimal.from(-2)
        );
        assertEquals(
            PreciseDecimalOperations.sub(
                PreciseDecimal.from(4),
                PreciseDecimal.from(4)
            ),
            PreciseDecimal.from(0)
        );
        assertEquals(
            PreciseDecimalOperations.sub(
                PreciseDecimal.from(-1),
                PreciseDecimal.from(-1)
            ),
            PreciseDecimal.from(0)
        );
        assertEquals(
            PreciseDecimalOperations.sub(
                PreciseDecimal.from(0),
                PreciseDecimal.from(3)
            ),
            PreciseDecimal.from(-3)
        );
        assertEquals(
            PreciseDecimalOperations.sub(
                PreciseDecimal.from(7),
                PreciseDecimal.from(7)
            ),
            PreciseDecimal.from(0)
        );
        assertEquals(
            PreciseDecimalOperations.sub(
                PreciseDecimal.from(3),
                PreciseDecimal.from(3)
            ),
            PreciseDecimal.from(0)
        );
    }

    @Test
    public final void mul() {
        assertEquals(
            PreciseDecimalOperations.mul(
                PreciseDecimal.from(4),
                PreciseDecimal.from(2)
            ),
            PreciseDecimal.from(8)
        );
        assertEquals(
            PreciseDecimalOperations.mul(
                PreciseDecimal.from(-1),
                 PreciseDecimal.from(2)
            ),
            PreciseDecimal.from(-2)
        );
        assertEquals(
            PreciseDecimalOperations.mul(
                PreciseDecimal.from(4),
                PreciseDecimal.from(0)
            ),
            PreciseDecimal.from(0)
        );
        assertEquals(
            PreciseDecimalOperations.mul(
                PreciseDecimal.from(-1),
                PreciseDecimal.from(0)
            ),
            PreciseDecimal.from(0)
        );
        assertEquals(
            PreciseDecimalOperations.mul(
                PreciseDecimal.from(7),
                PreciseDecimal.from(-3)
            ),
            PreciseDecimal.from(-21)
        );
        assertEquals(
            PreciseDecimalOperations.mul(
                PreciseDecimal.from(3),
                PreciseDecimal.from(-3)
            ),
            PreciseDecimal.from(-9)
        );
        assertEquals(
            PreciseDecimalOperations.mul(
                PreciseDecimal.from(7),
                PreciseDecimal.from(0)
            ),
            PreciseDecimal.from(0)
        );
        assertEquals(
            PreciseDecimalOperations.mul(
                PreciseDecimal.from(3),
                PreciseDecimal.from(0)
            ),
            PreciseDecimal.from(0)
        );
    }

    @Test
    public final void div() {
        assertEquals(
            PreciseDecimalOperations.div(
                PreciseDecimal.from(8),
                PreciseDecimal.from(4)
            ),
            PreciseDecimal.from(2)
        );
        assertEquals(
            PreciseDecimalOperations.div(
                PreciseDecimal.from(-2),
                PreciseDecimal.from(-1)
            ),
            PreciseDecimal.from(2)
        );
        assertEquals(
            PreciseDecimalOperations.div(
                PreciseDecimal.from(0),
                PreciseDecimal.from(4)
            ),
            PreciseDecimal.from(0)
        );
        assertEquals(
            PreciseDecimalOperations.div(
                PreciseDecimal.from(0),
                PreciseDecimal.from(-1)
            ),
            PreciseDecimal.from(0)
        );
        assertEquals(
            PreciseDecimalOperations.div(
                PreciseDecimal.from(-21),
                PreciseDecimal.from(7)
            ),
            PreciseDecimal.from(-3)
        );
        assertEquals(
            PreciseDecimalOperations.div(
                PreciseDecimal.from(-9),
                PreciseDecimal.from(3)
            ),
            PreciseDecimal.from(-3)
        );
        assertEquals(
            PreciseDecimalOperations.div(
                PreciseDecimal.from(0),
                PreciseDecimal.from(7)
            ),
            PreciseDecimal.from(0)
        );
        assertEquals(
            PreciseDecimalOperations.div(
                PreciseDecimal.from(0),
                PreciseDecimal.from(3)
            ),
            PreciseDecimal.from(0)
        );
    }

    @Test
    public final void rem() {
        assertEquals(
            PreciseDecimalOperations.rem(
                PreciseDecimal.from("-100.277"),
                PreciseDecimal.from(360)
            ),
            PreciseDecimal.from("-100.277")
        );
        assertEquals(
            PreciseDecimalOperations.rem(
                PreciseDecimal.from(360),
                PreciseDecimal.from(360)
            ),
            PreciseDecimal.from(0)
        );
        assertEquals(
            PreciseDecimalOperations.rem(
                PreciseDecimal.from("720.111"),
                PreciseDecimal.from(360)
            ),
            PreciseDecimal.from("0.111")
        );
        assertEquals(
            PreciseDecimalOperations.rem(
                PreciseDecimal.from(0),
                PreciseDecimal.from(360)
            ),
            PreciseDecimal.from(0)
        );
    }

    @Test
    public final void preciseCalculations() { 
        assertEquals(
            PreciseDecimalOperations.sum(
                PreciseDecimal.from("0.1"),
                PreciseDecimal.from("0.2")
            ),
            PreciseDecimal.from("0.3")
        );
        assertEquals(
            PreciseDecimalOperations.sum(
                PreciseDecimal.from("0.1234567890123456789012345678901"),
                PreciseDecimal.from("0.1234321003123432100312343210036")
            ),
            PreciseDecimal.from("0.2468888893246888889324688888937")
        );
        assertEquals(
            PreciseDecimalOperations.mul(
                PreciseDecimal.from("0.8937593473846237864238745"),
                PreciseDecimal.from("0.6986723567253716276345786345")
            ),
            PreciseDecimal.from("0.62444494958254521156041254853945406639389341840937025")
        );
        assertEquals(
            PreciseDecimalOperations.div(
                PreciseDecimal.from("0.6244449495825452115604125485"),
                PreciseDecimal.from("0.8937593473846237864238745")
            ),
            PreciseDecimal.from("0.6986723567253716276345786345")
        );
        assertEquals(
            PreciseDecimalOperations.sum(
                PreciseDecimal.from(1),
                PreciseDecimal.from("0.0000000000000000000000000001")
            ),
            PreciseDecimal.from("1.0000000000000000000000000001")
        );
        assertEquals(
            PreciseDecimalOperations.sub(
                PreciseDecimal.from("1.0000000000000000000000000001"),
                PreciseDecimal.from("0.0000000000000000000000000001")
            ),
            PreciseDecimal.from("1.0000000000000000000000000000")
        );
    }
}